SYNONYMS:

  Unity Catalog:
    - "Unity Catalog"
    - "unity catalog"
    - "UC"
    - "uc"
    - "Unity Catalog (UC)"
    - "Unity Catalogs"
    - "Unity Catalogs (UC)"

  UC Function:
    - "UC Function"
    - "UC function"
    - "Unity Catalog (UC) function"
    - "Unity Catalog Functions"
    - "UC Functions"
    - "UC functions"
    - "Unity Catalog (UC) functions"
    - "uc function"
    - "uc functions"
    - "Unity Catalog function"
    - "Unity Catalog functions"
    - "Unity Catalog Function"
  
  UC Functions:
    - "UC Function"
    - "UC function"
    - "Unity Catalog (UC) function"
    - "Unity Catalog Functions"
    - "UC Functions"
    - "UC functions"
    - "Unity Catalog (UC) functions"
    - "uc function"
    - "uc functions"
    - "Unity Catalog function"
    - "Unity Catalog functions"
    - "Unity Catalog Function"

  AI:
    - "genai"
    - "genAI"
    - "Genai"
    - "GenAI"
    - "GenAI framework"
    - "genai framework"
    - "Generative AI framework"
    - "genAI framework"
    - "GenAI Framework"
    - "genAi Framework"
    - "Artificial Intelligence"
    - "ai"
    - "Generative AI"

  GenAI:
    - "GenAI"
    - "genAI"
    - "Genai"
    - "genai"
    - "Generative AI"
    - "Generative AI (GenAI)"
    - "GenAI framework"
    - "genAI framework"
    - "GenAI Framework"
    - "genAi Framework"
    - "Generative AI framework"